export const interfaceMessages = `当前浏览器无法开启音频，仍可继续探索。	This browser cannot start audio. You can continue exploring.	このブラウザーでは音声を開始できません。探索は続けられます。	이 브라우저에서는 오디오를 시작할 수 없습니다. 탐험은 계속할 수 있습니다.	Este navegador no puede iniciar el audio. Puedes seguir explorando.
声音设置已保留 · 点击页面或按键后开启声音	Sound settings retained · Click the page or press a key to start audio	音声設定を保持しています · 画面をクリックするかキーを押すと音声が始まります	소리 설정이 유지됩니다 · 페이지를 클릭하거나 키를 눌러 소리를 시작하세요	Ajustes de sonido conservados · Haz clic en la página o pulsa una tecla para iniciar el audio
云间空隙	Between cloud banks	雲の切れ間	구름 사이	Entre nubes
NPC 根据前车速度与减速趋势保持车距；越大越提前减速。雨雪抓地力会进一步限制刹车能力。	NPCs follow the lead vehicle's speed and deceleration. Higher values brake earlier; rain and snow further limit braking grip.	NPC は前車の速度と減速傾向に合わせて車間を保ちます。値が大きいほど早めに減速し、雨や雪では制動力も下がります。	NPC는 앞차의 속도와 감속 추세에 맞춰 거리를 유지합니다. 값이 높으면 더 일찍 감속하며 비와 눈은 제동력을 제한합니다.	Los NPC mantienen la distancia según la velocidad y desaceleración del vehículo delantero. Valores altos anticipan el frenado; lluvia y nieve reducen el agarre.
NPC 最大减速度，实际值受轮胎抓地力限制。突然切入且距离不足时仍可能碰撞。	Maximum NPC deceleration, limited by tire grip. Sudden cut-ins with insufficient distance can still cause a crash.	NPC の最大減速度です。実際の制動力はタイヤのグリップに制限され、近距離の割り込みでは衝突する場合があります。	NPC의 최대 감속도이며 타이어 접지력에 따라 제한됩니다. 가까운 거리에서 갑자기 끼어들면 충돌할 수 있습니다.	Desaceleración máxima de los NPC, limitada por el agarre. Incorporaciones bruscas sin distancia suficiente pueden causar choques.
控制变道意愿和冷却速度。NPC 比较相邻车道拥堵与后车接近速度，先打灯再平顺变道；0 禁止主动变道。	Controls lane-change willingness and cooldown. NPCs compare neighboring congestion and approaching rear traffic, signal, then change lanes smoothly. 0 disables voluntary changes.	車線変更の積極性と待機時間を調整します。NPC は隣の混雑と後車の接近速度を確認し、合図して滑らかに移動します。0 で自発的な車線変更を停止します。	차선 변경 빈도와 대기 시간을 조절합니다. NPC는 옆 차로 정체와 뒤차 접근 속도를 확인하고 방향지시등을 켠 뒤 부드럽게 이동합니다. 0이면 자발적 변경을 끕니다.	Controla la frecuencia y espera de los cambios de carril. Los NPC comparan atascos y vehículos que se acercan por detrás, señalizan y cambian suavemente. 0 desactiva cambios voluntarios.
取出冰水并喝水	Take and drink water	冷水を取り出して飲む	찬물 꺼내 마시기	Sacar y beber agua
取水并喝水	Take and drink water	水を取り出して飲む	물 꺼내 마시기	Sacar y beber agua
停车补充冰水	Restock water while parked	停車中に冷水を補充	정차 중 냉수 보충	Reponer agua con el vehículo parado
补充冰水	Restock cold water	冷水を補充	냉수 보충	Reponer agua fría
正在喝水	Drinking water	水を飲んでいます	물을 마시는 중	Bebiendo agua
驻车中	Parked	停車中	정차 중	Estacionado
瓶装水	Bottled water	ボトル入りの水	생수	Agua embotellada
已饮用	Consumed	飲用済み	마신 양	Consumido
停车就座后取用 500 ml 瓶装水；开箱、拿瓶、喝水和收起约 4 秒。下车或换座会结束动作，未喝的水放回箱内。补水需停车，冷藏箱通电可保持低温。	Take a 500 ml bottle while seated and parked. Opening, drinking and putting it away takes about 4 seconds. Leaving or changing seats ends the action and returns untouched water. Restock while parked; power the cooler to keep water cold.	停車して着席中に 500 ml の水を取れます。開閉から飲み終わるまで約 4 秒です。降車や席の変更で中断し、未開封の水は戻します。補充は停車中に行い、冷蔵庫に通電すると低温を保ちます。	착석 및 정차 중 500 ml 물을 꺼냅니다. 꺼내 마시고 정리하는 데 약 4초가 걸립니다. 하차나 좌석 변경 시 중단되고 마시지 않은 물은 반환됩니다. 정차 중 보충하고 냉장고 전원을 켜 차갑게 유지하세요.	Toma una botella de 500 ml sentado y con el vehículo parado. Abrir, beber y guardarla tarda unos 4 segundos. Salir o cambiar de asiento termina la acción y devuelve el agua intacta. Repón agua al aparcar; enciende la nevera para mantenerla fría.
请调高总音量、全部音效及「发动机」音量。	Raise the master, effects and engine volumes.	マスター・効果音・エンジンの音量を上げてください。	전체, 효과음 및 엔진 음량을 높이세요.	Sube el volumen general, de efectos y del motor.
请调高总音量、全部音效及「发动机与换挡机械声」音量。	Raise the master, effects, engine and gearshift volumes.	マスター・効果音・エンジン・変速音の音量を上げてください。	전체, 효과음, 엔진 및 변속 음량을 높이세요.	Sube el volumen general, de efectos, del motor y de los cambios de marcha.
请调高总音量、全部音效及「本车喇叭」音量。	Raise the master, effects and player horn volumes.	マスター・効果音・自車ホーンの音量を上げてください。	전체, 효과음 및 내 차량 경적 음량을 높이세요.	Sube el volumen general, de efectos y de la bocina del vehículo.
音频设备已关闭，请点击强制开启声音重建。	The audio device is closed. Use Force audio recovery to rebuild it.	音声デバイスが閉じられました。「サウンドを強制復旧」で再構築してください。	오디오 장치가 닫혔습니다. 오디오 강제 복구를 눌러 다시 생성하세요.	El dispositivo de audio está cerrado. Usa Forzar recuperación de audio para recrearlo.
音频设备响应超时，请点击强制开启声音重试。	The audio device timed out. Use Force audio recovery to try again.	音声デバイスの応答がタイムアウトしました。「サウンドを強制復旧」で再試行してください。	오디오 장치 응답 시간이 초과되었습니다. 오디오 강제 복구로 다시 시도하세요.	El dispositivo de audio no respondió a tiempo. Usa Forzar recuperación de audio para reintentar.
音频恢复失败，请点击强制开启声音重试。	Audio recovery failed. Use Force audio recovery to try again.	音声の復旧に失敗しました。「サウンドを強制復旧」で再試行してください。	오디오 복구에 실패했습니다. 오디오 강제 복구로 다시 시도하세요.	No se pudo recuperar el audio. Usa Forzar recuperación de audio para reintentar.
3D 世界未启动 · 请重新加载页面	3D world did not start · Reload the page	3D ワールドを開始できませんでした · ページを再読み込みしてください	3D 월드를 시작하지 못했습니다 · 페이지를 새로고침하세요	El mundo 3D no se inició · Recarga la página
本机按键数据无法读取，已使用默认按键。	Saved key bindings could not be read. Default bindings are active.	保存されたキー設定を読み込めません。初期設定を使用しています。	저장된 키 설정을 읽을 수 없어 기본 설정을 사용합니다.	No se pudieron leer las teclas guardadas. Se usan las predeterminadas.
系统组合键保留，请选择其他按键。	This shortcut is reserved by the system. Choose another key.	この組み合わせはシステム用です。別のキーを選んでください。	시스템에서 사용하는 단축키입니다. 다른 키를 선택하세요.	El sistema reserva esta combinación. Elige otra tecla.
按键已生效并保存到当前浏览器。	Key binding applied and saved in this browser.	キー設定を適用し、このブラウザーに保存しました。	키 설정을 적용하고 이 브라우저에 저장했습니다.	Tecla aplicada y guardada en este navegador.
按键已生效，但浏览器不允许本机保存；刷新后会恢复默认。	Key binding applied, but browser storage is blocked. Reloading restores defaults.	キー設定を適用しましたが、ブラウザーが保存を拒否しています。再読み込みすると初期設定に戻ります。	키 설정은 적용되었지만 브라우저가 저장을 차단했습니다. 새로고침하면 기본값으로 돌아갑니다.	Tecla aplicada, pero el navegador bloquea el almacenamiento. Al recargar se restauran los valores predeterminados.
预设文件不能超过 64 KB。	Preset files must not exceed 64 KB.	プリセットファイルは 64 KB 以下にしてください。	프리셋 파일은 64 KB 이하여야 합니다.	El archivo de preajuste no debe superar los 64 KB.
文件不是有效的 JSON。	The file is not valid JSON.	有効な JSON ファイルではありません。	올바른 JSON 파일이 아닙니다.	El archivo no es un JSON válido.
预设格式或参数范围不正确，请使用本版（格式 20）导出的 JSON。当前设置未改变。	Invalid preset format or parameter range. Use JSON exported by this release (format 20). Current settings are unchanged.	プリセット形式または値の範囲が不正です。このバージョンで出力した JSON（形式 20）を使用してください。現在の設定は変更されていません。	프리셋 형식이나 값 범위가 올바르지 않습니다. 이 버전에서 내보낸 JSON(형식 20)을 사용하세요. 현재 설정은 변경되지 않았습니다.	Formato o rango de parámetros no válido. Usa JSON exportado por esta versión (formato 20). Los ajustes actuales no han cambiado.
本机预设数据过大，请先导出或清理。	Saved preset data is too large. Export or remove presets first.	保存されたプリセットが大きすぎます。先に書き出すか削除してください。	저장된 프리셋 데이터가 너무 큽니다. 먼저 내보내거나 삭제하세요.	Los preajustes guardados son demasiado grandes. Expórtalos o elimínalos primero.
本机预设数据不完整，原数据已保留。	Saved preset data is incomplete. The original data has been preserved.	保存されたプリセットが不完全です。元のデータは保持しています。	저장된 프리셋 데이터가 불완전합니다. 원본 데이터는 보존되었습니다.	Los datos de preajustes están incompletos. Se han conservado los originales.
最多保存 32 个预设，请先删除不需要的预设。	Up to 32 presets can be saved. Delete unused presets first.	保存できるプリセットは 32 個までです。不要なものを先に削除してください。	최대 32개의 프리셋을 저장할 수 있습니다. 불필요한 프리셋을 먼저 삭제하세요.	Puedes guardar hasta 32 preajustes. Elimina primero los que no necesites.
道路宽度、高度与密度数值必须在允许范围内。	Road width, height and density must be within the allowed ranges.	道路幅、高さ、密度は許容範囲内に設定してください。	도로 너비, 높이, 밀도는 허용 범위 내에 있어야 합니다.	El ancho, la altura y la densidad deben estar dentro de los rangos permitidos.
请检查道路宽度、车道与高度范围；车道不能过窄，上限不能低于下限。	Check road width, lanes and height ranges. Lanes must be wide enough, and each maximum must be at least its minimum.	道路幅、車線、高さの範囲を確認してください。車線を狭くしすぎず、上限は下限以上に設定してください。	도로 너비, 차로, 높이 범위를 확인하세요. 차로가 너무 좁으면 안 되며 최댓값은 최솟값 이상이어야 합니다.	Revisa el ancho, los carriles y las alturas. Los carriles deben ser suficientemente anchos y cada máximo debe ser igual o mayor que su mínimo.
上限不能低于下限。	The maximum must be at least the minimum.	上限は下限以上に設定してください。	최댓값은 최솟값 이상이어야 합니다.	El máximo debe ser igual o mayor que el mínimo.
沿当前分支寻找可衔接的大桥，可再次点击取消。	Searching this branch for a connected bridge. Click again to cancel.	現在の分岐に接続できる大橋を検索中です。もう一度押すとキャンセルできます。	현재 분기에서 연결 가능한 대교를 찾는 중입니다. 다시 누르면 취소됩니다.	Buscando un puente conectado en este ramal. Pulsa de nuevo para cancelar.
当前范围未找到可衔接桥位，请提高最大坡度或使用自然起伏。	No connected bridge site found within range. Increase the maximum grade or use natural elevation.	範囲内に接続可能な橋の場所が見つかりません。最大勾配を上げるか、自然な起伏を使用してください。	현재 범위에서 연결 가능한 교량 위치를 찾지 못했습니다. 최대 경사를 높이거나 자연 기복을 사용하세요.	No se encontró un puente conectado en el área. Aumenta la pendiente máxima o usa el relieve natural.
当前筛选下没有日志。	No logs match the current filter.	現在のフィルターに一致するログはありません。	현재 필터에 해당하는 로그가 없습니다.	No hay registros que coincidan con el filtro.
启动设置不完整。	Startup settings are incomplete.	起動時の設定が不完全です。	시작 설정이 불완전합니다.	Los ajustes de inicio están incompletos.
预设参数不正确。	Invalid preset parameters.	プリセットの値が不正です。	프리셋 매개변수가 올바르지 않습니다.	Los parámetros del preajuste no son válidos.
操作未完成：	Operation incomplete: 	操作を完了できませんでした：	작업을 완료하지 못했습니다: 	Operación incompleta:
可使用 JSON 导入导出。	You can use JSON import and export.	JSON の読み込み・書き出しを利用できます。	JSON 가져오기와 내보내기를 사용할 수 있습니다.	Puedes importar y exportar JSON.
`;
