import { expect, test } from '@playwright/test';
import { control, toggleSettings } from './settings';

test('drives gentle highways, preserves the route choice and streams a distant saddle', async ({ page }) => {
  test.setTimeout(120000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const metric = (name: string) => page.locator(`[data-metric="${name}"]`);
  const ready = async () => {
    await expect(metric('Road ready')).toHaveText('yes', { timeout: 30000 });
    await expect(metric('Pending / queued')).toHaveText('0 / 0', { timeout: 30000 });
  };
  await page.goto('/?seed=CLOUD-ROAD-001'); await ready();
  await (await control(page, page.locator('#road-type'))).selectOption('highway');
  await (await control(page, page.locator('#route-style'))).selectOption('1');
  await (await control(page, page.locator('#max-grade'))).fill('3');
  await (await control(page, page.getByRole('button', { includeHidden: true, name: '应用并返回起点' }))).click();
  await expect(metric('Road layout')).toHaveText('双向四车道'); await ready();
  await expect(metric('Hairpins')).toHaveText('0');
  await (await control(page, page.locator('#drive-toggle'))).click();
  await expect(metric('Vehicle speed')).toHaveText('0.0 km/h');
  await (await control(page, page.locator('#world'))).focus(); await page.keyboard.down('KeyW');
  await expect.poll(async () => parseFloat((await metric('Vehicle speed').textContent())!)).toBeGreaterThan(65);
  await page.keyboard.up('KeyW'); await page.keyboard.press('KeyP');
  expect(Math.abs(parseFloat((await metric('Road grade').textContent())!))).toBeLessThanOrEqual(3);
  expect(Math.abs(parseFloat((await metric('Road curvature').textContent())!))).toBeLessThanOrEqual(0.00084);
  await toggleSettings(page);
  await (await control(page, page.locator('#route-style'))).selectOption('5');
  await (await control(page, page.getByRole('button', { includeHidden: true, name: '应用并返回起点' }))).click();
  await expect(metric('Route style')).toHaveText('5 档 · 连续发卡弯'); await ready();
  await (await control(page, page.locator('#view-distance'))).selectOption('16');
  await expect(metric('Target chunks')).toHaveText('1089'); await ready();
  const before = await metric('Coordinates').textContent();
  await (await control(page, page.locator('#pass-view'))).click();
  await expect(metric('Coordinates')).not.toHaveText(before!, { timeout: 30000 }); await ready();
  await expect(metric('Mountain stage')).toHaveText('垭口');
  expect(Number(await metric('Hairpins').textContent())).toBeGreaterThan(0);
  expect(Math.abs(parseFloat((await metric('Road grade').textContent())!))).toBeLessThanOrEqual(3);
  await (await control(page, page.locator('#drive-toggle'))).click();
  await expect(metric('Travel mode')).toHaveText('driving');
  await expect(metric('Vehicle speed')).toHaveText('0.0 km/h');
  await (await control(page, page.locator('#world'))).focus(); await page.keyboard.down('KeyW');
  await expect.poll(async () => parseFloat((await metric('Vehicle speed').textContent())!)).toBeGreaterThan(20);
  await page.keyboard.up('KeyW');
  expect(errors).toEqual([]);
});
