import { expect, test } from '@playwright/test';
import { control, toggleSettings } from './settings';

test('applies winding levels, drives them and preserves choices during far streaming and recovery', async ({ page }) => {
  test.setTimeout(120000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const metric = (name: string) => page.locator(`[data-metric="${name}"]`);
  const ready = async () => {
    await expect(metric('Road ready')).toHaveText('yes', { timeout: 30000 });
    await expect(metric('Pending / queued')).toHaveText('0 / 0', { timeout: 30000 });
  };
  await page.goto('/?seed=CLOUD-ROAD-001'); await ready();
  await (await control(page, page.locator('#terrain-kind'))).selectOption('forest');
  await (await control(page, page.locator('#route-style'))).selectOption('3');
  await (await control(page, page.getByRole('button', { includeHidden: true, name: '应用并返回起点' }))).click();
  await expect(metric('Route style')).toHaveText('3 档 · 盘山折返'); await ready();
  expect(Number(await metric('Hairpins').textContent())).toBeGreaterThanOrEqual(2);
  const home = await metric('Coordinates').textContent();
  await (await control(page, page.locator('#hairpin-view'))).click();
  await expect(metric('Coordinates')).not.toHaveText(home!); await ready();
  await (await control(page, page.locator('#view-distance'))).selectOption('16');
  await expect(metric('Target chunks')).toHaveText('1089'); await ready();
  await expect(metric('Active chunks')).toHaveText('1089');
  await (await control(page, page.locator('#terrain-kind'))).selectOption('desert');
  await (await control(page, page.locator('#route-style'))).selectOption('5');
  await (await control(page, page.getByRole('button', { includeHidden: true, name: '应用并返回起点' }))).click();
  await expect(metric('Route style')).toHaveText('5 档 · 连续发卡弯'); await ready();
  expect(Number(await metric('Bridges').textContent())).toBeGreaterThan(0);
  expect(Number(await metric('Bridge piers').textContent())).toBeGreaterThan(10);
  await expect(page.locator('#view-distance')).toHaveValue('16');
  await (await control(page, page.locator('#drive-toggle'))).click();
  await expect(metric('Travel mode')).toHaveText('driving');
  await (await control(page, page.locator('#world'))).focus(); await page.keyboard.down('KeyW');
  await expect.poll(async () => parseFloat((await metric('Vehicle speed').textContent())!)).toBeGreaterThan(20);
  await page.keyboard.up('KeyW');
  await page.keyboard.press('KeyP');
  await page.locator('#world').evaluate(canvas => {
    const extension = (canvas as HTMLCanvasElement).getContext('webgl2')!.getExtension('WEBGL_lose_context')!;
    extension.loseContext(); setTimeout(() => extension.restoreContext(), 1000);
  });
  await expect(page.locator('#error')).toBeVisible(); await expect(page.locator('#error')).toBeHidden();
  await expect(page.locator('#route-style')).toHaveValue('5');
  await toggleSettings(page);
  await (await control(page, page.locator('#road-type'))).selectOption('highway');
  await (await control(page, page.locator('#road-width'))).selectOption('10');
  await (await control(page, page.getByRole('button', { includeHidden: true, name: '应用并返回起点' }))).click(); await ready();
  await expect(metric('Road layout')).toHaveText('双向四车道');
  await expect(metric('Route style')).toHaveText('5 档 · 连续发卡弯');
  expect(Number(await metric('Hairpins').textContent())).toBeGreaterThan(0);
  await (await control(page, page.locator('#service-view'))).click();
  await expect(metric('Service areas')).toHaveText('1', { timeout: 30000 }); await ready();
  await (await control(page, page.locator('#seed'))).fill('CLIFF-REPLAY');
  await (await control(page, page.getByRole('button', { includeHidden: true, name: '加载种子' }))).click();
  await expect(metric('Seed')).toHaveText('CLIFF-REPLAY'); await ready();
  await expect(page.locator('#route-style')).toHaveValue('5');
  expect(errors).toEqual([]);
});
