import { expect, test } from '@playwright/test';
import { closeSettings, control, ignite } from './settings';

test('generates a level signal intersection, pauses its clock and saves traffic preferences', async ({ page }, info) => {
  test.setTimeout(120000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const metric = (name: string) => page.locator(`[data-metric="${name}"]`);
  await page.goto('/?seed=SIGNAL-JUNCTION');
  await (await control(page, page.locator('#graphics-preset'))).selectOption('economy');
  await (await control(page, page.locator('#road-type'))).selectOption('avenue');
  await (await control(page, page.locator('#terrain-kind'))).selectOption('meadow');
  await (await control(page, page.locator('#route-style'))).selectOption('0');
  await (await control(page, page.locator('#mountain-height'))).selectOption('range');
  await page.locator('#mountain-min').fill('100'); await page.locator('#mountain-max').fill('100');
  await (await control(page, page.locator('#max-grade'))).fill('0');
  await (await control(page, page.locator('#crossroads'))).check();
  await page.locator('#crossroad-interval').fill('1.5');
  await page.getByRole('button', { name: '应用并返回起点', exact: true }).click();
  await expect(metric('Road ready')).toHaveText('yes', { timeout: 30000 });
  await (await control(page, page.locator('#junction-view'))).click();
  await expect(metric('Signal intersections')).not.toHaveText('0', { timeout: 30000 });
  await expect(metric('Road ready')).toHaveText('yes', { timeout: 30000 });
  await closeSettings(page); await page.locator('#drive-toggle').click();
  await expect(page.locator('#signal-guidance')).toBeVisible();
  await ignite(page); await page.keyboard.down('KeyW');
  await expect.poll(async () => Number((await page.locator('#signal-guidance').textContent())?.match(/·\s*(\d+) m/)?.[1] ?? 1000), { timeout: 20000 }).toBeLessThan(30);
  await page.keyboard.up('KeyW'); await page.keyboard.down('Space'); await page.waitForTimeout(1800); await page.keyboard.up('Space');
  await page.screenshot({ path: info.outputPath('signal-road.png') });
  await (await control(page, page.locator('#signal-crossGreen'))).fill('10');
  await expect(page.locator('#signal-settings-status')).toContainText('主路红灯 17 s');
  const time = await metric('Signal time').textContent(); await page.waitForTimeout(300);
  await expect(metric('Signal time')).toHaveText(time!);
  await page.locator('#rules-enabled').uncheck(); await expect(page.locator('#traffic-warning')).toBeHidden();
  await (await control(page, page.locator('#preset-name'))).fill('Signal drive'); await page.locator('#preset-save').click();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('cloud-roads.presets.v20')!)[0]);
  expect(saved.world.crossroads).toBe(true); expect(saved.world.crossroadInterval).toBe(1500);
  expect(saved.settings['signal-crossGreen']).toBe(10); expect(saved.settings['rules-enabled']).toBe(false);
  await (await control(page, page.locator('#signal-crossGreen'))).fill('7'); await page.locator('#rules-enabled').check();
  await (await control(page, page.locator('#preset-apply'))).click();
  await (await control(page, page.locator('#signal-crossGreen'))).scrollIntoViewIfNeeded();
  await expect(page.locator('#signal-crossGreen')).toHaveValue('10'); await expect(page.locator('#rules-enabled')).not.toBeChecked();
  await expect(page.locator('#signal-settings-status')).toContainText('主路红灯 17 s');
  await (await control(page, page.locator('#road-type'))).selectOption('highway');
  await expect(page.locator('#crossroads')).toBeDisabled(); await expect(page.locator('#crossroad-interval')).toBeDisabled();
  expect(errors).toEqual([]);
});
