import { expect, test } from '@playwright/test';

test('operates headlights and wipers, freezes controls in dialogs and adapts to motorcycles', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const metric = (name: string) => page.locator(`[data-metric="${name}"]`);
  await page.goto('/');
  await page.locator('#vehicle-kind').selectOption('sedan');
  await page.locator('#driving-view').selectOption('cockpit');
  await page.locator('#weather-kind').selectOption('storm');
  await page.locator('#vehicle-lights').selectOption('off');
  await page.locator('#suspension-damping').fill('130');
  await expect(page.locator('#drive-toggle')).toBeEnabled({ timeout: 30000 });
  await page.locator('#drive-toggle').click();
  await expect(metric('Vehicle lights')).toHaveText('off');
  await expect(metric('Wiper rate')).toHaveText('1.6');
  await expect.poll(async () => Number(await metric('Wiper sweep').textContent())).toBeGreaterThan(0.2);
  await page.keyboard.press('KeyL'); await expect(metric('Vehicle lights')).toHaveText('low');
  await page.keyboard.press('KeyL'); await expect(metric('Vehicle lights')).toHaveText('high');
  await page.keyboard.press('KeyB'); await expect(metric('Wiper sweep')).toHaveText('0.000');
  await page.keyboard.press('KeyB'); await expect(page.locator('#vehicle-wipers-status')).toHaveText('雨刮 · 间歇');
  await page.keyboard.press('KeyP');
  const sweep = await metric('Wiper sweep').textContent();
  await page.keyboard.press('KeyL'); await expect(metric('Vehicle lights')).toHaveText('high');
  await page.locator('#release-open').click(); await page.keyboard.press('KeyB');
  await expect(metric('Wiper sweep')).toHaveText(sweep!);
  await page.getByRole('button', { name: '关闭公告', exact: true }).click();
  await page.locator('#controls-toggle').click();
  await page.locator('#vehicle-kind').selectOption('motorcycle');
  await expect(page.locator('#vehicle-wipers')).toBeDisabled();
  await expect(metric('Wiper rate')).toHaveText('0.0');
  await expect(metric('Suspension damping')).toHaveText('130%');
  await page.locator('#vehicle-kind').selectOption('coach');
  await expect(page.locator('#vehicle-wipers')).toBeEnabled();
  await expect(page.locator('#vehicle-lights')).toHaveValue('high');
  await expect(page.locator('#vehicle-wipers')).toHaveValue('intermittent');
  await expect(page.locator('#suspension-damping-value')).toHaveText('130%');
  await page.locator('#vehicle-wipers').selectOption('high');
  await page.locator('#controls-toggle').click(); await page.locator('#world').focus(); await page.keyboard.press('KeyP');
  await expect.poll(async () => Number(await metric('Wiper sweep').textContent())).toBeGreaterThan(0.2);
  expect(errors).toEqual([]);
});
