import { expect, test } from '@playwright/test';

test('renders moving rain against the sky, freezes it when paused, and keeps selectors reachable on mobile', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('/');
  await expect(page.locator('[data-metric="Pending / queued"]')).toHaveText('0 / 0', { timeout: 30_000 });
  await page.locator('#cloud-toggle').click();
  await page.locator('#time-preset').selectOption('0');
  await page.locator('#sun-view').click();
  await page.locator('#weather-kind').selectOption('rain');
  const clip = { x: 700, y: 200, width: 500, height: 300 };
  const rain = await page.screenshot({ clip });
  await page.waitForTimeout(300);
  expect(await page.screenshot({ clip })).not.toEqual(rain);
  await page.locator('#pause').click();
  const frozen = await page.screenshot({ clip });
  await page.waitForTimeout(300);
  expect(await page.screenshot({ clip })).toEqual(frozen);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#weather-kind').selectOption('overcast');
  await page.locator('#time-preset').selectOption('-100');
  await expect(page.locator('#time-preset')).toBeInViewport();
  await expect(page.locator('[data-metric="Weather"]')).toHaveText('多云');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('changes weather and time in place, lights road sections and preserves choices on reload', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const metric = (name: string) => page.locator(`[data-metric="${name}"]`);
  await page.goto('/');
  await expect(page.locator('#weather-kind')).toBeAttached();
  await expect(metric('Road ready')).toHaveText('yes', { timeout: 30_000 });
  await expect(metric('Pending / queued')).toHaveText('0 / 0', { timeout: 30_000 });
  const coordinates = await metric('Coordinates').textContent();
  await page.locator('#weather-kind').selectOption('rain');
  await page.locator('#time-preset').selectOption('150');
  await expect(metric('Weather')).toHaveText('雨天');
  await expect(metric('Light phase')).toHaveText('夜晚');
  await expect(page.locator('#daylight')).toHaveValue('150');
  await expect(metric('Coordinates')).toHaveText(coordinates!);
  await page.locator('#cloud-toggle').click();
  await page.locator('#weather-kind').selectOption('fog');
  await expect(metric('Fog near / far')).toHaveText('35 / 420 m');
  await page.locator('#weather-kind').selectOption('clear');
  await page.locator('#lights-view').click();
  await expect.poll(async () => Number(await metric('Local lights').textContent())).toBeGreaterThan(0);
  await page.locator('#lights-toggle').click();
  await expect(metric('Local lights')).toHaveText('0');
  await page.locator('#seed').fill('WEATHER-REPLAY');
  await page.getByRole('button', { name: '加载种子' }).click();
  await expect(metric('Seed')).toHaveText('WEATHER-REPLAY');
  await expect(page.locator('#time-preset')).toHaveValue('150');
  await expect(page.locator('#weather-kind')).toHaveValue('clear');
  await expect(page.locator('#lights-toggle')).toHaveAttribute('aria-pressed', 'false');
  await page.locator('#daylight').fill('-100');
  await expect(metric('Light phase')).toHaveText('清晨');
  await expect(page.locator('#time-preset')).toHaveValue('-100');
  await page.locator('#daylight').fill('42');
  await expect(page.locator('#time-preset')).toHaveValue('custom');
  await expect(page.locator('#error')).toBeHidden();
  expect(errors).toEqual([]);
});

test('enters a lit tunnel, shelters from rain, and restores the scene after context loss', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const metric = (name: string) => page.locator(`[data-metric="${name}"]`);
  await page.goto('/');
  await expect(page.locator('#tunnel-view')).toBeEnabled({ timeout: 30_000 });
  await page.locator('#weather-kind').selectOption('rain');
  await page.locator('#tunnel-view').click();
  await page.locator('#speed').fill('20');
  await page.locator('#world').focus();
  await page.keyboard.down('KeyW');
  await expect(metric('Tunnel shelter')).toHaveText('100%', { timeout: 10_000 });
  await page.keyboard.up('KeyW');
  await page.locator('#pause').click();
  await expect(metric('Rain visible')).toHaveText('no');
  await expect.poll(async () => Number(await metric('Local lights').textContent())).toBeGreaterThan(0);
  await page.locator('#world').evaluate(canvas => {
    const extension = (canvas as HTMLCanvasElement).getContext('webgl2')!.getExtension('WEBGL_lose_context')!;
    extension.loseContext();
    setTimeout(() => extension.restoreContext(), 1000);
  });
  await expect(page.locator('#error')).toBeVisible();
  await expect(page.locator('#error')).toBeHidden();
  await expect(metric('Rain visible')).toHaveText('no');
  await page.getByRole('button', { name: '返回起点', exact: true }).click();
  await expect(metric('Tunnel shelter')).toHaveText('0%');
  await expect(metric('Rain visible')).toHaveText('yes');
  expect(errors).toEqual([]);
});
