import { expect, test } from '@playwright/test';

test('reports ground biomes independently of flight altitude and reproduces them after seed reload', async ({ page }) => {
  const metric = (name: string) => page.locator(`[data-metric="${name}"]`);
  const names = ['Ground biome', 'Ground altitude', 'Ground slope', 'Snow cover', 'Snow line', 'Temperature', 'Humidity'];
  const values = () => Promise.all(names.map((name) => metric(name).textContent()));
  await page.goto('/');
  await expect(metric('Road ready')).toHaveText('yes', { timeout: 20_000 });
  await expect(metric('Pending / queued')).toHaveText('0 / 0', { timeout: 20_000 });
  await expect(metric('Ground biome')).toHaveText(/^(山谷|森林|岩石|高山|雪区)$/);
  const original = await values();
  const altitude = Number((await metric('Coordinates').textContent())!.split(',')[1]);
  await page.locator('#world').focus();
  await page.keyboard.down('Space');
  await expect.poll(async () => Number((await metric('Coordinates').textContent())!.split(',')[1])).toBeGreaterThan(altitude + 80);
  await page.keyboard.up('Space');
  expect(await values()).toEqual(original);
  await page.locator('#seed').fill('A-SECOND-MOUNTAIN');
  await page.getByRole('button', { name: '加载种子' }).click();
  await expect(metric('Seed')).toHaveText('A-SECOND-MOUNTAIN');
  await expect(metric('Road ready')).toHaveText('yes', { timeout: 20_000 });
  await expect(metric('Snow line')).not.toHaveText(original[4]!);
  await page.locator('#seed').fill('CLOUD-ROAD-001');
  await page.getByRole('button', { name: '加载种子' }).click();
  await expect(metric('Seed')).toHaveText('CLOUD-ROAD-001');
  await expect(metric('Road ready')).toHaveText('yes', { timeout: 20_000 });
  await expect(metric('Pending / queued')).toHaveText('0 / 0', { timeout: 20_000 });
  expect(await values()).toEqual(original);
});

test('renders WebGL, resizes, flies, pauses and exposes debug telemetry', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await expect(page.locator('#fps')).not.toHaveText('—');
  await expect(page.locator('#error')).toBeHidden();
  await page.locator('#world').focus();
  await page.keyboard.press('F3');
  await expect(page.locator('#debug')).toBeVisible();
  const before = await page.locator('#position').textContent();
  await page.keyboard.down('KeyW');
  await expect(page.locator('#position')).not.toHaveText(before!);
  await page.keyboard.up('KeyW');
  await page.keyboard.press('KeyP');
  await expect(page.locator('#notice')).toContainText('已暂停');
  const stopped = await page.locator('#position').textContent();
  await page.keyboard.down('KeyW');
  await page.waitForTimeout(250);
  await page.keyboard.up('KeyW');
  await expect(page.locator('#position')).toHaveText(stopped!);
  await page.keyboard.press('KeyP');
  await page.setViewportSize({ width: 1100, height: 720 });
  await expect.poll(() => page.locator('#world').evaluate((canvas: HTMLCanvasElement) => canvas.width / canvas.height)).toBeCloseTo(1100 / 720, 2);
  expect(errors).toEqual([]);
});

test('streams a 30 km flight, rebases, recycles, and returns to the same seed', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  const metric = (name: string) => page.locator(`[data-metric="${name}"]`);
  await page.goto('/');
  await expect(metric('Road ready')).toHaveText('yes', { timeout: 20_000 });
  await expect(metric('Pending / queued')).toHaveText('0 / 0', { timeout: 20_000 });
  await expect(metric('Active chunks')).toHaveText('289');
  const originalAltitude = await page.locator('#altitude').textContent();
  await page.locator('#world').focus();
  await page.keyboard.press('F3');
  await page.locator('#speed').fill('1200');
  await page.locator('#world').focus();
  await page.keyboard.down('ControlLeft');
  await page.keyboard.down('KeyD');
  await expect.poll(async () => Number((await metric('Coordinates').textContent())?.split(',')[0]), { timeout: 40_000 }).toBeGreaterThan(30_128);
  await page.keyboard.up('KeyD');
  await page.keyboard.up('ControlLeft');
  await expect(metric('Pending / queued')).toHaveText('0 / 0', { timeout: 20_000 });
  expect(Number(await metric('Origin rebases').textContent())).toBeGreaterThanOrEqual(5);
  expect(Number(await metric('Active chunks').textContent())).toBe(289);
  expect(Number(await metric('Allocated meshes').textContent())).toBeLessThanOrEqual(578);
  const local = (await metric('Local X / Z').textContent())!.split('/').map(Number);
  expect(Math.hypot(...local)).toBeLessThan(5000);
  await page.getByRole('button', { name: '返回起点', exact: true }).click();
  await expect(page.locator('#position')).toHaveText('128 / 128');
  await expect(page.locator('#altitude')).toHaveText(originalAltitude!);
  await page.getByRole('button', { name: '地形线框' }).click();
  await expect(page.locator('#wireframe')).toHaveAttribute('aria-pressed', 'true');
  await page.locator('#seed').fill('A-SECOND-MOUNTAIN');
  await page.getByRole('button', { name: '加载种子' }).click();
  await expect(metric('Seed')).toHaveText('A-SECOND-MOUNTAIN');
  await expect(page.locator('#altitude')).not.toHaveText(originalAltitude!);
  await page.locator('#seed').fill('CLOUD-ROAD-001');
  await page.getByRole('button', { name: '加载种子' }).click();
  await expect(metric('Seed')).toHaveText('CLOUD-ROAD-001');
  await expect(page.locator('#altitude')).toHaveText(originalAltitude!);
  await expect(metric('Road ready')).toHaveText('yes', { timeout: 20_000 });
  await expect(metric('Pending / queued')).toHaveText('0 / 0', { timeout: 20_000 });
  expect(Number(await metric('Allocated meshes').textContent())).toBe(289);
  expect(errors).toEqual([]);
});

test('clears held keys on blur and ignores flight keys while editing the seed', async ({ page }) => {
  await page.goto('/');
  await expect(page.locator('#fps')).not.toHaveText('—');
  await page.locator('#world').focus();
  await page.keyboard.down('KeyW');
  await page.evaluate(() => window.dispatchEvent(new Event('blur')));
  await page.waitForTimeout(300);
  const stopped = await page.locator('#position').textContent();
  await page.waitForTimeout(300);
  await expect(page.locator('#position')).toHaveText(stopped!);
  await page.keyboard.up('KeyW');
  await page.locator('#seed').focus();
  await page.keyboard.type('wasd');
  await page.waitForTimeout(300);
  await expect(page.locator('#position')).toHaveText(stopped!);
});
